apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/sazzadk/argocd.git
    targetRevision: HEAD
    path: deployments
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
